theme: jekyll-theme-midnight

plugins:
  - jekyll-seo-tag

webmaster_verifications:
  google: uGDkT9PwZFzSUIVtB2FkqyeU_gqWasx9JvuU2ZyPCpc
  bing: FEE532B29EB0D0D939C09ACDC50A96B2
  alexa: 1234
  yandex: 8f2129ef77147489
  baidu: 1234

